#!/bin/sh -e

libdir="/Users/admin/Desktop/nghttp2-spm/build-out/ios_sim/lib"
if [ -d "$libdir/.libs" ]; then
    libdir="$libdir/.libs"
fi

export CGO_CFLAGS="-I/Users/admin/Desktop/nghttp2-spm/_upstream/nghttp2/lib/includes -I/Users/admin/Desktop/nghttp2-spm/build-out/ios_sim/lib/includes "
export CGO_CPPFLAGS=""
export CGO_LDFLAGS="-L$libdir "
export LD_LIBRARY_PATH="$libdir"
export DYLD_LIBRARY_PATH="$libdir"
export GODEBUG=cgocheck=0
"$@"
